# Generated by Django 3.0.5 on 2022-01-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, null=True)),
                ('montant', models.FloatField(default=0)),
                ('tel', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'unique_together': {('nom', 'tel')},
            },
        ),
        migrations.CreateModel(
            name='LastLogin',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provisioning',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCanada',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(default=0)),
                ('transfer', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBurundi',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(default=0)),
                ('transfer', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
